name: "vjmakers"
description: "VJC’s Project: Makers are a group of students who are interested in innovating and making all kinds of things."
url: "https://vjmakers.github.io"
env: "development"
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
exclude:
  - "LICENSE"
  - "README.md"
  - "Gemfile"
  - "package.json"
gems:
  - "jekyll-sitemap"
  - "jekyll-last-modified-at"
  - "octopress-minify-html"
